services:
    sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "H@r8585926068"
        platform: "linux/amd64"
        ports:
            - "1433:1433"